version: '3.4'
services:
  app-db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build: ./app
    ports:
      - "8000:80"
    expose:
      - '8000'
networks:
  network1:
    name: app_default
    external: true
volumes:
  data:
