version: '3.9'
services:
  app-db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - appnetwork
  app:
    build: ./app
    ports:
      - "8000:80"
    expose:
      - '8000'
    networks:
      - appnetwork

networks:
  appnetwork:
    name: app_default
    external: true

volumes:
  data:
    name: db-default
