version: '3.8'
services:
  app-db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - appnet
  app:
    build: ./app
    ports:
      - "8000:80"
    expose:
      - '8000'
    networks:
      - appnet

networks:
  appnet:
    name: app_default
    external: true

volumes:
  data:
